trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

# Stage 1: Build
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    displayName: "Run Build"
    steps:
    - script: |
        echo Building the application...
        mkdir build
        echo "Build files" > build/output.txt
      displayName: "Build the application"

# Stage 2: Test
- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  jobs:
  - job: TestJob
    displayName: "Run Tests"
    steps:
    - script: |
        echo Running tests...
        echo "All tests passed!"
      displayName: "Run unit tests"

- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Test
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    displayName: "Deploy Application"
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo Deploying the application...
              echo "Application deployed successfully!"
            displayName: "Deploy to production"