# Customized pipeline
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release

steps:
- script: echo "Starting the pipeline!"
  displayName: 'Run a one-line script'

- script: |
    echo "Building the project..."
    echo "Build configuration: $(buildConfiguration)"
  displayName: 'Run a multi-line script'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/output.zip
    replaceExistingArchive: true
  displayName: 'Archive build outputs'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: drop
    pathToPublish: $(Build.ArtifactStagingDirectory)
  displayName: 'Publish build artifacts'